### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [icure/freehealth-connector#4]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/icure-io/freehealth-connector/blob/7f987c9724b30c933be8cc3887c9b198fb5baf9a/decompiled/3.19.1/be/fgov/ehealth/rn/commons/business/v1/CBSSFaultType.java

**Comment by aduchate** [comment]
I fail to see how this file could contain any sensitive information. It looks like your automated threat detection tool is overly enthusiastic.
